pdh_counters:
    metricprefix: 'myprefix'
    interval: 5
    counters:
        eng-.*:
            - path: '\Processor(*)\% Processor Time'
        .*bmc.*:
            - path: '\Processor(*)\% User Time'
    # The names of the hosts to collect counters from. This list should not contain duplicates.
    # If duplicates exist, only the first instance of the duplicated item will be processed.
    hostnames:
        - 'host1'
        - 'host2'