pdh_counters:
    metricprefix: 'myprefix'
    interval: 5
    counters:
        .*:
            - path: '\Processor(*)\% Processor Time'
        .*host.*:
            - path: '\Processor(*)\% User Time'
    # The names of the hosts to collect counters from. This list should not contain duplicates.
    # If duplicates exist, only the first instance of the duplicated item will be processed.
    # Note that localhost will be replaced with the actual hostname of the machine executing
    # the pdhexport application.
    hostnames:
        - 'localhost'
        - 'host2'